# Generated by Django 4.2.2 on 2023-06-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="아이디 생성일"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=255, unique=True, verbose_name="사용자 이메일"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("남성", "남성"), ("여성", "여성"), ("밝히고 싶지 않음", "밝히고 싶지 않음")],
                error_messages="필수 입력 값입니다.",
                max_length=10,
                verbose_name="성별",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(max_length=100, unique=True, verbose_name="사용자 닉네임"),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=255, verbose_name="비밀번호"),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="마지막 회원정보 수정일"),
        ),
    ]
