# Generated by Django 4.2.2 on 2023-06-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.PositiveIntegerField(verbose_name="사용자 나이"),
        ),
    ]
